version: "3.7"

services:
  htmx-server:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: production
    container_name: htmx
    environment:
      DIRECTUS_HOST: http://directus:8055
      PORT: 8080
    ports:
      - 8080:8080

  directus:
    image: directus/directus:10.7.1
    container_name: directus
    ports:
      - 8055:8055
    volumes:
      - directus_database:/directus/database
      - directus_uploads:/directus/uploads
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: true

volumes:
  directus_database:
  directus_uploads:
